### ISSUE TITLE
Preprocessor support

### ISSUE THREAD

**Issue by jslegers** [yannickl88/css-tokenizer#1]
Can I assume this library suports the complete CSS3 syntax?

Also, it would be nice to have a solution for tokenizing LESS, PostCSS and especially SCSS alongside CSS. The only somewhat decent solution for SCSS written in PHP that I know of is [**leafo/scssphp**](http://leafo.net/scssphp/), which has only partial support for SCSS 3.3. Judging by its version number, [**leafo/lessphp**](http://leafo.net/lessphp/) has the same problem. Any plans to add this sometime in the future?

**Comment by yannickl88** [comment]
I only support the CSS2 syntax as seen in the [tests](https://github.com/yannickl88/css-tokenizer/blob/master/test/TokenizerTest.php). It was originally made to be a base for a CSS to LESS converter for my company, however, somewhere along the line we decided to do it by hand so it was never actually used.

As you might have guessed, I do not use it for anything at the moment so I have no intention of expanding the tokenizer. You are welcome to send pull requests of course.

**Comment by yannickl88** [comment]
Because this project has seen another use internally at our company, additional support has been added for LESS (because this is the pre-processor flavor we chose). Steps have been taken to further the language support. So CSS3 will most likely be further supported.
